web: 
  hosts:
    worker1:
      ansible_host: 192.168.2.17
    worker2:
      ansible_host: 192.168.2.18
  vars:
      ansible_connection: ssh
      ansible_user: codellya

boss: 
  hosts:
    master:
      ansible_host: 192.168.2.16
  vars:
      ansible_connection: ssh
      ansible_user: codellya

